repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args:
          - '--maxkb=200'
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: go-test
        name: run tests
        entry: bash -c 'go test ./...'
        language: system
        always_run: true
        pass_filenames: false
