name: Tests

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  main:
    strategy:
      matrix:
        go-version: [ 1.22.x, 1.23.x ]
        os-version: [ ubuntu-latest ]
    runs-on: ${{ matrix.os-version }}
    name: GoLang ${{ matrix.go-version }}, ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install GoLang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
      - name: Run Tests
        run: go test ./...
      - name: Run Linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
      - name: Run Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
